spring.application.name=ICP Connect Backend
server.port=8848

spring.datasource.url=jdbc:postgresql://localhost:5432/icp_connect
spring.datasource.username=postgres
spring.datasource.password=cevin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET}
# Access token expiration (15 minutes)
app.jwt.access-exp-ms=900000
# Refresh token expiration (7 days)
app.jwt.refresh-exp-ms=604800000

# Spring Mail SMTP Settings (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_SMTP}
spring.mail.password=${PASSWORD_SMTP}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Multipart Upload Settings (Increase for videos/large images)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Chat Message Encryption (AES-256-GCM)
app.encryption.key=${CHAT_ENCRYPTION_KEY}
